### ISSUE TITLE
kanji looking different in the wallpaper than in WK 

### ISSUE THREAD

**Issue by zosiu** [Hexagenic/wanikaniwallpaper-js#3]
This kanji:
[WK](https://www.wanikani.com/kanji/%E7%9B%B4) /
[jisho](http://beta.jisho.org/search/%E7%9B%B4%20%23kanji)

shows up in the wallpaper differently than the above links (missing part of the "lion")
![wk_wallpaper_fix](https://cloud.githubusercontent.com/assets/405732/7134255/74657f10-e29b-11e4-86e1-cd710bc78ab7.png)
![wk_fix](https://cloud.githubusercontent.com/assets/405732/7134256/74671e38-e29b-11e4-9df8-f65d9b34981e.png)

**Comment by Hexagenic** [comment]
It's a font issue. I'm going to see if I can get the font list to be the same as on wanikani. My site seems to render it as simplified, while wanikani uses the traditional character.

http://en.wiktionary.org/wiki/%E7%9B%B4

**Comment by Hexagenic** [comment]
Resolved in 41403e7a485b0fa416c549eb74b934254bd2d3e2
Use Meiryo as default, as in WaniKani.
