### ISSUE TITLE
Use of cookies makes for a potential leak of tokens

### ISSUE THREAD

**Issue by mjvmroz** [Hexagenic/wanikaniwallpaper-js#4]
The application makes use of legacy API tokens which have write access to accounts. With settings currently stored in cookies, that provides a potential attacker a lot of opportunities to steal API tokens which unfortunately have a lot more access than they need to.

A switch to `localStorage` is imperfect because the application isn't secured with TLS, but it nonetheless dramatically increases the attack complexity required to steal a user's WK API token.

Use of cookies was more than understandable at the time of original writing, as the web storage API wasn't nearly as widely supported in 2014, but it is now (~97% according to [caniuse](https://caniuse.com/#feat=namevalue-storage)).

**Comment by Hexagenic** [comment]
Merged pull request.
